mirror:
  image: bitnami/git:latest
  rules:
  - if: $CI_PIPELINE_SOURCE == "schedule"
  - if: $CI_PIPELINE_SOURCE == "web"
  variables:
    GIT_STRATEGY: none
    SOURCE: github.com/bittner/bittner.git
    TARGET: gitlab.com/bittner/bittner.git
  before_script:
  - git clone --mirror https://${SOURCE} clone
  - cd clone
  - git remote rename origin github
  - git remote add gitlab https://oauth2:${GITLAB_TOKEN}@${TARGET}
  script:
  - git lfs fetch github --all
  - git lfs push gitlab --all
  - git push gitlab --force --prune 'refs/heads/*:refs/heads/*' 'refs/tags/*:refs/tags/*'
