mirror:
  image: bitnami/git:latest
  rules:
  - if: $CI_PIPELINE_SOURCE == "schedule"
  - if: $CI_PIPELINE_SOURCE == "web"
  variables:
    GIT_STRATEGY: none
    SOURCE: github.com/bittner/bittner.git
    TARGET: gitlab.com/bittner/bittner.git
  before_script:
  - git clone https://${SOURCE} clone
  - cd clone
  - git remote add gitlab https://gitlab-ci-token:${CI_JOB_TOKEN}@${TARGET}
  script:
  - git push --force gitlab main
