on:
  schedule:
  - cron: '0 2 * * *'
  workflow_dispatch:
jobs:
  mirror:
    runs-on: codeberg-small
    steps:
    - name: Sync repository from GitHub
      env:
        CI_JOB_TOKEN: ${{ secrets.FORGEJO_TOKEN }}
        SOURCE: github.com/bittner/bittner.git
        TARGET: codeberg.org/bittner/bittner.git
      run: |
        git clone https://${SOURCE} clone
        cd clone
        git remote add codeberg https://token:${CI_JOB_TOKEN}@${TARGET}
        git push --force codeberg main
